ch2_quick_ref:
  site_id: 37e6d6de
  update_key: FezOd2AoAsSXAuNxOSdEezdzLc5TayhiVb8WDaMDmso
  url: https://37e6d6de.ht-ml.app/
ch3_quick_ref:
  site_id: 45a785ec
  update_key: Bf-BCNRh4pXQeZ878X7-gwEYiDapY4ANw6fh6jokiVw
  url: https://45a785ec.ht-ml.app/
course_index:
  site_id: 7848bafa
  update_key: HMBDjm18ow-14rE6x5FYJmd7mDcVLjSrpSnFAIL4ofc
  url: https://7848bafa.ht-ml.app/
glossary:
  site_id: 3e997043
  update_key: e_uEXaCGfLHehBmiA_1QVxxTRPamtCAUGXG9xEC7_yE
  url: https://3e997043.ht-ml.app/
lesson_0001:
  site_id: 2769bf05
  update_key: i7NR7ArwU9NbHKYvXjLp9T1tTfq1XhNd0vGOssTtEKw
  url: https://2769bf05.ht-ml.app/
lesson_0002:
  site_id: e9fea6ef
  update_key: oFXSGtFYBAZaqg48rh2f1dPAQQtHs2nhIcroxJbqFrg
  url: https://e9fea6ef.ht-ml.app/
lesson_0003:
  site_id: f9d1ffa4
  update_key: -IYUPVKFe-BBwAclvUljLXruvTIWIq7LoFTRLKdDHVc
  url: https://f9d1ffa4.ht-ml.app/
state_machine:
  site_id: 1c0af16d
  update_key: uWMBmttv-N_axr0jykXDHtZUab8lRen7XtsAghf4dcU
  url: https://1c0af16d.ht-ml.app/
chapter4_lesson:
  site_id: 50a64951
  update_key: NQzcyOnZhF2LBtK8Ub7Y_Bue2X5oZ481bguELC9O9_g
chapter4_reference:
  site_id: 56ad0f9a
  update_key: CcAYgvVt7-V5WN1zxee7F5sZF7NlSnkymQiE0mJEk4E

lesson_0005:
  site_id: e9366b4b
  update_key: HvYNSi6_M4KCDcB95Ot0OEQCSa9KVHH3gwhh41HkGog
  url: https://e9366b4b.ht-ml.app/
chapter5_reference:
  site_id: aaa51794
  update_key: _TZe5-ejYC2l0q_kQiBoBp5ufx-d-jt-SThwQgqwF3Y
  url: https://aaa51794.ht-ml.app/

lesson_0006:
  site_id: db7e5380
  update_key: bSFIk0xTaNsKKyxBfuDB_q1p8eXYhgwx9VmUkexRzJo
  url: https://db7e5380.ht-ml.app/
chapter6_reference:
  site_id: 85187eed
  update_key: XFe0i3YD2RaxVcrDxVTuyY2xZsu6pfPyJ4dqO65Sgkw
  url: https://85187eed.ht-ml.app/
