live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

  [cursor.style]
  blinking = "On"
  shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.glyph_offset]
  x = 0
  y = 0

  [font.italic]
  family = "JetBrainsMono Nerd Font"

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.offset]
  x = 0
  y = 0

[mouse]
hide_when_typing = true

  [[mouse.bindings]]
  action = "PasteSelection"
  mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "Full"
dynamic_title = true
startup_mode = "Maximized"

  [window.dimensions]
  columns = 160
  lines = 80

  [window.padding]
  x = 0
  y = 0

# Colors (Oxocarbon)
# Source https://vimcolorschemes.com/nyoom-engineering/oxocarbon.nvim

# Default colors
[colors.primary]
background = '#1b1b1b'
foreground = '#ffffff'

[colors.cursor]
text = '#161616' 
cursor = '#78a9ff'

# Normal colors
[colors.normal]
black   = '#161616'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  

# Bright colors
[colors.bright]
black   = '#525252'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  
