# NOTES:
# - (keyboard)
#  - Ctrl+Shift+Space toggle into vi mode
#  - Ctrl+Shift+Enter spawn new instance
#  - Ctrl+Shift+b backward search
#  - Ctrl+Shift+f forward search


[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

  [cursor.style]
  blinking = "On"
  shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

  [font.bold]
  family = "FiraCode Nerd Font"
  style = "Bold"

  [font.glyph_offset]
  x = 0
  y = 0

  [font.italic]
  family = "JetBrainsMono Nerd Font"

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

  [font.offset]
  x = 0
  y = 0

[mouse]
hide_when_typing = true

  [[mouse.bindings]]
  action = "PasteSelection"
  mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Full"
dynamic_title = true
startup_mode = "Maximized"

  [window.dimensions]
  columns = 160
  lines = 80

  [window.padding]
  x = 0
  y = 0

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# Colors (Oxocarbon)
# Source https://vimcolorschemes.com/nyoom-engineering/oxocarbon.nvim
[colors.primary]
background = '#1b1b1b'
foreground = '#ffffff'

[colors.cursor]
text = '#161616' 
cursor = '#78a9ff'

[colors.normal]
black   = '#161616'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  

[colors.bright]
black   = '#525252'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  

[colors.search]
matches = { foreground = '#e1e5f6', background = '#34457f' } 
focused_match = { foreground = '#ffffff', background = '#33b1ff' } 

[colors.hints]
start = { foreground = '#ffffff', background = '#ff7eb6' }
end = { foreground = '#ffffff', background = '#ee5396' }

[colors.line_indicator]
foreground = '#ffffff'
background = '#161616'

[colors.footer_bar]
foreground = '#ffffff'
background = '#1f1f1f'

[colors.selection]
text = '#1b1b1b'       
background = '#78a9ff' 

[colors.vi_mode_cursor]
text = '#1b1b1b'  
cursor = '#78a9ff'

[colors.dim]
black   = '#0f0f0f'
red     = '#712b2b'
green   = '#5f6f3a'
yellow  = '#a17e4d'
blue    = '#456877'
magenta = '#704d68'
cyan    = '#4d7770'
white   = '#8e8e8e'
